// Project catalog — single source of truth for the AnEntrypoint expo.

export const projects = [
    // gm package — the factory + its rust internals
    { code:'001', title:'gm', sub:'convinces agents they are a state machine', cat:'gm', stars:15, color:'g-green', url:'https://github.com/AnEntrypoint/gm', tags:['flagship','state-machine','discipline'], install:'npx gm', body:'reach for gm when an agent is drifting — looping, hallucinating tools, skipping verification. drop it into any session and the model walks PLAN, EXECUTE, EMIT, VERIFY on every turn instead of guessing. it lives inside the agent loop, not beside it. exists because faith-based prompting stops being funny the second it ships to prod.' },
    { code:'002', title:'rs-exec', sub:'MCP code execution in Rust', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/rs-exec', tags:['rust','mcp','polyglot'], install:'cargo install rs-exec', body:'used whenever gm needs to actually run something — JS, Go, Rust, Python, C/C++, bash. mounts as an MCP server, the agent calls it like any other tool. picked over node-shelling-out because rust starts faster and dies cleaner when a probe goes wrong.' },
    { code:'003', title:'rs-search', sub:'RRF fusion + tokenization crate behind rs-plugkit\'s search', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/rs-search', tags:['rust','search'], install:'-', body:'not a standalone tool — no CLI, no MCP server, no binary. it\'s the dependency-free rlib rs-plugkit\'s wasm host links in for the actual ranking math: reciprocal rank fusion across ranked id lists (with an identifier-boost weight for camelCase/snake_case-shaped queries) and the tokenizer that splits camelCase/punctuation into searchable pieces. reach for it when you\'re touching how rs-plugkit merges or tokenizes search results, not when you want a search tool to run directly.' },
    { code:'004', title:'rs-codeinsight', sub:'tree-sitter codebase report generator for AI coding tools', cat:'gm', stars:1, color:'g-flame', url:'https://github.com/AnEntrypoint/rs-codeinsight', tags:['rust','tree-sitter','analysis'], install:'cargo install rs-codeinsight', body:'first call when an agent lands in an unfamiliar repo. one binary, 13 languages via tree-sitter, under 200ms even on 500-file projects — outputs a single ~900-token report with stack, routes, data models, env vars, conventions, test coverage, and health issues, no caps on the lists. exists so gm spends its tokens reasoning about the code, not re-deriving what the project even is one grep at a time.' },
    { code:'005', title:'rs-learn', sub:'cross-session memory for gm', cat:'gm', stars:1, color:'g-flame', url:'https://github.com/AnEntrypoint/rs-learn', tags:['rust','memory','learning'], install:'-', body:'queried at the start of any task that smells familiar. captures what worked last time, replays it before the agent re-discovers it. used because solving the same quirk twice in two sessions is a tax this stack refuses to pay.' },
    { code:'006', title:'rs-plugkit', sub:'the wasm engine gm actually runs on', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/rs-plugkit', tags:['rust','plugins'], install:'-', body:'the plugkit-core wasm guest that agentplug-runner loads to drive every gm dispatch — the FSM graph, the spool ABI, the git/prd/mutable verbs, all compiled in here. reach for it when you\'re changing how gm\'s phase machine or verb surface behaves, not when you\'re writing a new plugin — that\'s plugsdk. there\'s no standalone CLI or JS wasm-host fallback anymore; agentplug is the only host that loads it.' },
    { code:'007', title:'plugsdk', sub:'host-side loader for Claude Code\'s plugin format', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/plugsdk', tags:['sdk','plugins','portable'], install:'-', body:'reach for it when your own app needs to load and run plugins authored in Claude Code\'s plugin format, not just Claude Code itself. it reads every documented component off disk — manifest, hooks, skills, commands, agents, MCP/LSP server configs, monitors, themes, marketplace catalogs — and dispatches your app\'s events through the plugins\' hooks with the same subprocess execution, JSON I/O, matcher filtering, and precedence rules (deny > defer > ask > allow) Claude Code itself follows. it does not author plugins and ships no UI — it is the loader and hook dispatcher, nothing else.' },
    { code:'009', title:'agentplug', sub:'the wasm plugin runtime gm actually runs on', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/agentplug', tags:['wasm','runtime','plugins'], install:'-', body:'the thing gm is not visible to you: one native runner hosts N wasm plugin modules (gm, libsql, bert, tree-sitter) and mediates calls between them, plus a direct-CDP browser driver and a native task registry — no per-host JS wrapper, no playwright dependency. every gm dispatch this session made went through it. reach for it when a plugin needs to run the same way across hosts without reimplementing the loader each time.' },
    { code:'010', title:'lean', sub:'an 8-phase, 5-gate method for agent-driven work', cat:'gm', stars:1, color:'g-flame', url:'https://github.com/AnEntrypoint/lean', tags:['method','skill','contracts'], install:'.claude/skills/lean/', body:'a sibling discipline to gm: the contract (types, names, signatures) is the durable artifact, not a spec file — a task is shaped, contracted, built, and checked by an agent that has not seen the implementation, with failure routed back to the phase that owns it. no comments, no example-based unit tests, no durable spec outside git. reach for it when you want gm-shaped rigor without gm\'s own state-machine framing.' },

    // gm ports — gm wired into every coding agent
    { code:'017', title:'agentgui', sub:'multi-agent GUI for AI coding assistants', cat:'gm-tools', stars:16, color:'g-sky', url:'https://github.com/AnEntrypoint/agentgui', tags:['gui','agents','desktop'], install:'npx agentgui', body:'open it when you run more than one coding agent and your terminal is a wreck. Claude Code, Gemini CLI, OpenCode — every session in one window with shared context. one npx, every agent. exists because alt-tabbing between four CLIs is not a workflow.' },
    { code:'018', title:'freddie', sub:'open JS agent harness with a dashboard on top', cat:'gm-tools', stars:5, color:'g-sky', url:'https://github.com/AnEntrypoint/freddie', tags:['dashboard','agents','observability'], install:'-', body:'reach for it when an agent needs more than a REPL — a full harness with 70 auto-discovered tools, a gateway fronting 17 platform adapters (discord, slack, whatsapp, telegram, matrix, and more), 8 pluggable memory providers, cron and batch runners, and an ACP server for IDE integration. the live dashboard is one view into that — the pane that shows what the fleet is doing — not the whole project anymore. built on pi-mono, xstate, and anentrypoint-design.' },
    { code:'019', title:'casey', sub:'animal-disease reporting over WhatsApp, for rural South Africa', cat:'gm-tools', stars:0, color:'g-sky', url:'https://github.com/AnEntrypoint/casey', tags:['agents','whatsapp','discord'], install:'-', body:'reach for it when the reporters are farmers and field workers texting in on WhatsApp, in their own language, about sick or dead livestock — casey greets them, gathers a structured report without interrogating them, and gives the organising team one observable case per report. built on freddie and thatcher, so the agent harness and the audited case system of record are already wired; the dashboard is a plain-language "needs you now" queue, not a ticket tracker. used when the people on both ends may not be technical and the priority stays with them, not with disease rules.' },
    { code:'020', title:'gmweb', sub:'Dockerized remote dev desktop for agentgui + opencode + gm', cat:'gm-tools', stars:2, color:'g-sky', url:'https://github.com/AnEntrypoint/gmweb', tags:['web','wasm','agents'], install:'-', body:'stand it up when you want a full remote desktop — VNC, web terminal, file manager — running Claude CLI, agentgui, and opencode behind one Traefik/nginx front door with HTTP Basic Auth on everything but the desktop route. it\'s a LinuxServer Webtop container with a supervisor that health-checks and auto-restarts those services, plus a background version-check loop that watches npm/GitHub for updates and bounces the affected service in place. used when the goal is a disposable, browser-reachable box that already has the agent stack installed, not a bare shell you have to provision by hand.' },
    { code:'021', title:'godot-kit', sub:'agent skill for live Godot 4.x debugging', cat:'gm-tools', stars:1, color:'g-sky', url:'https://github.com/AnEntrypoint/godot-kit', tags:['godot','gamedev','agents'], install:'-', body:'run `npx godot-kit .` inside a Godot 4.x project and it drops in an Agent Skill plus two HTTP bridges — one in the running game (port 6009) for live scene-tree inspection and GDScript eval, one in the editor (port 6008) for undoable property edits. no CLI binary, no editor plugin marketplace, no DAP — the agent just talks HTTP. reach for it when an agent needs to see and poke a running Godot game instead of writing .gd files blind.' },

    // ml — tiny NPC dialog model, trained and run on our own iron
    { code:'013', title:'tai', sub:'fast desktop + ESP32 inference for the PLE TinyLM, in Rust', cat:'gm', stars:1, color:'g-flame', url:'https://github.com/AnEntrypoint/tai', tags:['rust','inference','edge'], install:'cargo build --release', body:'runs the 28.9M-parameter Per-Layer-Embedding NPC dialog model this stack trains itself — memory-mapped weights, int4 group-quantized matvecs on AVX2+FMA (scalar fallback), the output head split across every core with rayon. the same model generates at 9.5 tok/s on an ESP32-S3, so a NPC brain fits on a microcontroller, not just a desktop. reach for it when a trained checkpoint from traintai needs to actually talk back somewhere with no GPU in the loop.' },
    { code:'014', title:'traintai', sub:'training pipeline for tai\'s NPC dialog model', cat:'gm', stars:1, color:'g-flame', url:'https://github.com/AnEntrypoint/traintai', tags:['rust','training','rl'], install:'uv run python src/round.py', body:'everything that produces the SillyTavern-shaped NPC dialog model tai runs: an economy simulation and survival-sim self-play tournament generate grounded training conversations, GRPO reinforcement learning scores adherence (persona, intent, grounding, action correctness against an oracle), and an autonomous multi-generation loop runs action-forge, tournament, prepare, SFT, GRPO, forge, then eval end to end with no human in the loop. exports straight to the int4 binary tai\'s runtime loads. consumed by tai as a git submodule.' },

    // voice + avatars
    { code:'030', title:'zellous', sub:'serverless Discord over Nostr', cat:'voice', stars:4, color:'g-flame', url:'https://github.com/AnEntrypoint/zellous', tags:['voice','opus','realtime'], install:'npm i zellous', body:'a full Discord-shaped chat and voice app with no backend — servers, channels, roles, threads, invite links — running entirely against public Nostr relays. voice is native WebRTC (mesh under 3 peers, elected SFU hub above that), signaling rides Nostr events, and there\'s no account system: your key is your identity, held in a browser extension or localStorage, with no password-reset path if you lose it. reach for it when you want Discord-like presence for a community without standing up any infrastructure at all — the whole client is a static site, and the protocol layer ships separately as wireweave.' },
    { code:'031', title:'wireweave', sub:'nostr + WebRTC networking SDK', cat:'voice', stars:1, color:'g-sky', url:'https://github.com/AnEntrypoint/wireweave', tags:['nostr','webrtc','sdk'], install:'npm i wireweave', body:'imported by anything in 247420 that needs peer discovery and realtime transport without a signaling server or a backend. nostr finds the peers; WebRTC carries voice, binary data channels, and now a full serverless chat layer — channels, servers, roles/bans, DMs, reactions, forum posts — all riding the same relay connection. used so voice and social features stay deployable without an ops team.' },
    { code:'032', title:'streamtts', sub:'RWKV-7 live-tuning trainer for Claude Code traces', cat:'voice', stars:0, color:'g-mascot', url:'https://github.com/AnEntrypoint/streamtts', tags:['webgpu','tts','browser'], install:'npm i streamtts', body:'reach for it when a model should keep learning from an agent\'s own session traces instead of sitting frozen — it pulls Claude Code JSONL through ccsniff, state-tunes an RWKV-7 1.5B model in real time (pretrained weights frozen, gradients only through per-layer recurrent state + a hypernetwork), and serves the result as an OpenAI-compatible endpoint. one Rust binary, no GPU cluster required.' },
    { code:'033', title:'dialog-generator', sub:'archived — Discord voice bot (STT+LLM+TTS+blendshapes)', cat:'voice', stars:1, color:'g-mascot', url:'https://github.com/AnEntrypoint/dialog-generator', tags:['tts','vrm','animation'], install:'-', body:'archived. grew from a text-to-audio+lipsync bridge into diagen, a full real-time Discord voice bot: joins a voice channel, transcribes with Whisper, runs the reply through chatjimmy\'s LLM, synthesizes with LuxTTS, and streams the audio (plus blendshape animation via /api/generate) back in. still usable as a library or HTTP API for text-to-audio-plus-facial-rig, but the shipped product is the Discord bot, not a bare TTS+VRM bridge.' },
    { code:'034', title:'lipsync-sdk', sub:'avatar lipsync SDK', cat:'voice', stars:0, color:'g-mascot', url:'https://github.com/AnEntrypoint/lipsync-sdk', tags:['lipsync','sdk'], install:'-', body:'imported wherever a 3D avatar already has a voice track and the mouth needs to track it in real time. the low-level piece dialog-generator builds on.' },

    // data + memory + search
    { code:'042', title:'codebasesearch', sub:'semantic code search via Jina embeddings + LanceDB', cat:'data', stars:3, color:'g-acid', url:'https://github.com/AnEntrypoint/codebasesearch', tags:['search','codebase'], install:'-', body:'point it at a repo and ask english questions about the code instead of grepping for literal strings — "where do we handle auth", not "where does the string foo appear". runs as a CLI (`bunx codebasesearch`) or an MCP server Claude Code can call directly; single-shot, no daemon, auto-indexes into a local LanceDB store on first run and gitignores it. everything stays on-disk, no data leaves the machine.' },
    { code:'043', title:'adaptogen', sub:'skill that improves any skill via run/critique/land, no state files', cat:'data', stars:2, color:'g-acid', url:'https://github.com/AnEntrypoint/adaptogen', tags:['state-machine','dag','memory'], install:'-', body:'reach for it when a skill needs hardening but you don\'t trust a self-review to catch anything real — it dispatches one subagent to actually run the skill and a second, isolated one to adversarially hunt for fault, then lands every evidence-backed fix as a real edit and re-runs to confirm it held (reverting on regression). no side files, no state tracking: git is the entire durability layer, a commit is the checkpoint. used when a skill (including adaptogen itself) needs to get better under its own power.' },
    { code:'044', title:'busybase', sub:'drop-in self-hosted Supabase alternative', cat:'data', stars:1, color:'g-acid', url:'https://github.com/AnEntrypoint/busybase', tags:['sqlite','http','database'], install:'-', body:'reach for it when a project wants the Supabase JS v2 API — auth, tables, realtime — without Docker, Postgres, or a hosted bill. single Bun binary over libSQL/SQLite, Ed25519 keypair auth anonymous-first, built-in SMTP, pluggable hooks. used when "just give me a database with a URL" has grown into "and auth and realtime too."' },
    { code:'045', title:'statekit', sub:'persistent compute on a content-addressable FS', cat:'data', stars:0, color:'g-acid', url:'https://github.com/AnEntrypoint/statekit', tags:['storage','content-addressable','compute'], install:'-', body:'used when compute should survive a restart by addressing its state by content, not by location. a content-addressable filesystem layer that lets long-running work pick up exactly where it left off. the durable floor under the agent stacks that cannot afford to recompute from zero.' },

    // tooling + bridges
    { code:'050', title:'ccsniff', sub:'Claude Code JSONL to events, history API, and audits', cat:'tooling', stars:2, color:'g-sun', url:'https://github.com/AnEntrypoint/ccsniff', tags:['observability','events'], install:'npm i ccsniff', body:'tail Claude Code\'s session JSONL and get a Node EventEmitter back, or a CLI to grep/rollup/tail sessions directly. used when something needs to react to what an agent is doing live — dashboards, hook triggers, audit logs — or when the sessions themselves need auditing: --git-discipline/--search-discipline/--verb-bypass-discipline/--spool-discipline catch gm sessions bypassing their own verb surfaces. also ships a mountable Express router (history snapshot/search/SSE stream) that AgentGUI\'s live client runs on, and an --unsloth export for turning session history into fine-tuning data. exists because Claude Code is otherwise an opaque box.' },
    { code:'051', title:'acptoapi', sub:'unified chain SDK + any-to-any AI protocol bridge', cat:'tooling', stars:5, color:'g-sun', url:'https://github.com/AnEntrypoint/acptoapi', tags:['shim','openai','acp'], install:'-', body:'reach for it when a codebase is wired to one SDK shape (OpenAI, Anthropic, Gemini) and needs to hit a different backend without a rewrite - point the SDK at acptoapi and it resolves a `provider/model` string to a concrete backend and streams back in the wire format the client expects. handles comma-separated fallback chains and named queues (an xstate v5 machine drives the descent, with per-provider backoff skipping known-down providers and a capability matrix keeping incapable models out of the chain). runs as a server-free programmatic SDK or as an HTTP server with OpenAI/Anthropic/Gemini-compatible endpoints; freddie, casey, and thebird all depend on it as the single source of truth for resolution and chaining instead of reimplementing it locally.' },
    { code:'052', title:'thebird', sub:'browser-native multi-instance web OS', cat:'tooling', stars:0, color:'g-sun', url:'https://github.com/AnEntrypoint/thebird', tags:['bridge','anthropic','gemini'], install:'-', body:'reach for it when you want a full desktop environment running entirely client-side — windows, a taskbar, an in-browser POSIX shell, a real filesystem (OPFS, falling back to IndexedDB) — with no server and no build step. each instance gets its own Service Worker so multiple thebirds open in one tab never share state. ships freddie-host, an in-page agent with vector search and code insight over the OS itself, plus a user-authored app system for extending it. serverless in the literal sense: clone it, point a static file server at docs/, open os.html.' },
    { code:'053', title:'research', sub:'three claude.ai/gemini CLI flows over playwriter cookies', cat:'tooling', stars:0, color:'g-sun', url:'https://github.com/AnEntrypoint/research', tags:['cli','research','playwright'], install:'-', body:'reach for it when a browser-only AI surface needs to run headless from a script. three flows share playwriter-extracted cookies: fire a prompt at claude.ai and stream the answer, ingest a github repo via gitingest and feed the digest into fable for a no-tools rewrite, or generate an image on gemini.google.com and save it as PNG. used over API keys when the account only has a logged-in browser tab, not a token.' },
    { code:'054', title:'agent-gsuite', sub:'MCP server for Google Docs, Sheets, Gmail, Drive', cat:'tooling', stars:1, color:'g-sun', url:'https://github.com/AnEntrypoint/agent-gsuite', tags:['agents','gsuite'], install:'-', body:'reach for it when an agent needs to actually work inside a Google account — 53 MCP tools covering docs, sheets, gmail, drive, and apps script, plus an HTTP/SSE streaming mode with Google OAuth login for remote multi-user connections. used when the work crosses from "thinking about it" to "putting it in the user\'s inbox".' },
    { code:'055', title:'audit-cc-tail', sub:'fingerprint the Claude model behind a session', cat:'tooling', stars:2, color:'g-sun', url:'https://github.com/AnEntrypoint/audit-cc-tail', tags:['observability','audit','models'], install:'-', body:'reach for it when you need to know which model variant actually ran — not which one was requested. reads behaviour out of Claude Code session tails and tells the family members apart. used when a regression might be a silent model swap, not your code.' },
    { code:'056', title:'thatcher', sub:'config-driven application framework SDK', cat:'tooling', stars:0, color:'g-sun', url:'https://github.com/AnEntrypoint/thatcher', tags:['sdk','framework','config'], install:'-', body:'pulled in when an app should be described by config instead of wired by hand — the framework SDK extracted from moonlight and reused across casey and friends. used when the same application shape keeps getting rebuilt and it is time to declare it once.' },

    // p2p
    { code:'061', title:'spoint', sub:'multiplayer game server + netcode SDK', cat:'p2p', stars:2, color:'g-purple', url:'https://github.com/AnEntrypoint/spoint', tags:['discovery','p2p'], install:'-', body:'reach for it when a multiplayer game needs an authoritative server without hand-rolling netcode. Jolt physics, hot-reloadable apps for entity/world logic, a Three.js client, and lag compensation built in. one server handles both modes — `/` for real multiplayer over WebSocket, `/?singleplayer` runs the identical server code inside a Web Worker on the same origin. exports to a fully static, backend-less bundle for itch.io or GitHub Pages when a host with no server is the target.' },

    // web + content + media
    { code:'070', title:'flatspace', sub:'flat-file CMS', cat:'web', stars:3, color:'g-sun', url:'https://github.com/AnEntrypoint/flatspace', tags:['cms','static','yaml'], install:'npx flatspace build', body:'used whenever content should be diffable, reviewable in a PR, and deployable from a push. content lives as YAML in git, flatspace builds the static site. this site uses it. reached for over a database CMS when "git is the database" is the right answer.' },
    { code:'071', title:'247420', sub:'the proof of concept that runs live', cat:'web', stars:5, color:'g-green', url:'https://github.com/AnEntrypoint/247420', tags:['poc','spa','broadcast'], install:'git clone github.com/AnEntrypoint/247420', body:'the site you\'re reading. used as the pressure test for every gm and gm-cc pattern — real users, real timing, a broadcast TV system synced to the second. when something works here, the pattern ships. when it breaks here, it gets fixed before anyone else inherits it.' },
    { code:'072', title:'design', sub:'247420 design system', cat:'web', stars:1, color:'g-green', url:'https://github.com/AnEntrypoint/design', tags:['design-system','tokens'], install:'-', body:'imported by every 247420-shaped surface so they all look like they came from the same building. layered surfaces, monospace labels, loud content inside quiet chrome. used over a generic UI kit because the visual rhythm here is part of the brief, not the wrapping.' },
    { code:'075', title:'showpick', sub:'weekly TV schedule builder for the broadcast', cat:'web', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/showpick', tags:['video','ai-curation'], install:'-', body:'pulls video collections from archive.org and builds them into weekly schedule files, then deploys the day\'s slate straight into 247420\'s schedule.json. reach for it when the broadcast needs a week of programming lined up without hand-picking every slot — preprocess fetches, build_schedule assembles the week, deploy writes the flat format the player reads.' },
    { code:'076', title:'floosie', sub:'universal stream processing platform', cat:'web', stars:0, color:'g-acid', url:'https://github.com/AnEntrypoint/floosie', tags:['streams','pipeline'], install:'npm i floosie', body:'reach for it when data needs to move through a pipeline and you don\'t want to hand-write the glue — 98 typed chunks (json, binary, media, network, scalars) each with its own codec, composable processors/operators (mux, split, batch, throttle, parallel), and a CLI for wiring files, websockets, and stdio together without touching the plumbing yourself.' },
    { code:'077', title:'assets', sub:'3D asset library', cat:'web', stars:1, color:'g-purple', url:'https://github.com/AnEntrypoint/assets', tags:['3d','assets'], install:'-', body:'pulled in by the avatar / VRM / lipsync stack so every project is loading the same models, textures, and scenes instead of hunting for new ones. the shared shelf.' },
    { code:'078', title:'mux', sub:'AI media sorter for the community\'s meme drops', cat:'web', stars:0, color:'g-sun', url:'https://github.com/AnEntrypoint/mux', tags:['discord','media','ingest'], install:'-', body:'reach for it when a pile of saved images/videos needs sorting for schwepe content instead of a human scrolling through them by hand. runs each file through GLM-4.5V, scores it, and moves the misses into deleted_images/deleted_media with a report — batched so it doesn\'t blow through API limits. the filter between "someone dumped a folder of media" and "this is what\'s actually schwepe."' },

    // browser sandboxes — real Linux + desktops that run in a tab
    { code:'080', title:'webix', sub:'Blink-backed x86_64 Linux userspace emulator, browser + Node', cat:'sandbox', stars:0, color:'g-purple', url:'https://github.com/AnEntrypoint/webix', tags:['emulator','linux','xstate'], install:'-', body:'reach for it when code needs a real Linux userspace and the only runtime you can count on is a browser tab or Node. ~280 lines of host code over a 240KB Blink wasm that owns the CPU, MMU, ~150 syscalls, signals, and fork/clone/sockets — no hand-rolled JS instruction decoder, syscall ABI, or VFS. the XState kernel/machines wrapper that used to sit on top was ripped out as unused indirection; the engine the rest of the sandbox family is built on.' },
    { code:'081', title:'portabox', sub:'in-browser x86_64 Linux sandbox SDK', cat:'sandbox', stars:0, color:'g-purple', url:'https://github.com/AnEntrypoint/portabox', tags:['sandbox','x86','wasm'], install:'-', body:'embed it when an app needs to run untrusted code with nothing to install — a self-contained x86_64 Linux box that lives inside the page. built on webix. used when "run this safely, client-side" has to be true, not aspirational.' },
    { code:'082', title:'portacastle', sub:'a cloud desktop that runs in your browser, backed by real Vercel Sandbox VMs', cat:'sandbox', stars:0, color:'g-purple', url:'https://github.com/AnEntrypoint/portacastle', tags:['desktop','sandbox','browser'], install:'-', body:'reach for it when you want a full remote desktop — window manager, terminal, code-server, file browser, even X11 apps like Firefox and GIMP — streamed into a tab with no local install. each workspace is a real isolated Linux microVM (Vercel Sandbox / Firecracker), not a client-only simulation: a Next.js backend brokers the sandbox, Postgres tracks workspaces and a warm pool, and Xpra/WSS carry the terminal and X11 streams back to the browser. explicitly marked vibecoded/proof-of-concept by its own README, not production-hardened.' },
    { code:'083', title:'cors', sub:'pluggable fetch over public CORS proxies', cat:'sandbox', stars:0, color:'g-purple', url:'https://github.com/AnEntrypoint/cors', tags:['fetch','cors','xstate'], install:'-', body:'drop it in when browser fetch keeps hitting CORS walls and you need the request to land anyway. an XState-driven fetch SDK that fails over across public CORS proxies until one works. the unglamorous piece that lets the in-browser stacks actually reach the network.' },
];

export const categories = [
    { id:'gm',       label:'gm — the factory + rust internals', color:'g-green',  blurb:'reach for these when an agent needs to plan, execute, search, orient, or remember. gm runs the loop; rs-exec, rs-search, rs-codeinsight, rs-learn, and rs-plugkit are the rust services it dispatches into during the loop.' },
    { id:'gm-tools', label:'gm ports — gm in every coding agent', color:'g-mascot', blurb:'pick the port that matches the editor or CLI you already live in. same loop, same discipline, every surface. agentgui is for when you run more than one at once.' },
    { id:'voice',    label:'voice + avatars',                color:'g-mascot', blurb:'used when a project needs to be heard or seen speaking — push-to-talk rooms, in-browser TTS, lipsync, VRM avatars opening their mouths.' },
    { id:'data',     label:'data, search & memory',          color:'g-acid',   blurb:'used when an agent needs memory that knows when, or search that understands what — temporal graphs and semantic codebase search.' },
    { id:'tooling',  label:'observability & shims',          color:'g-sun',    blurb:'reach for these when you need to watch an agent, point existing code at a different model, or bring an OpenAI-shaped client into the ACP world.' },
    { id:'p2p',      label:'peer-to-peer',                   color:'g-purple', blurb:'shared as a single link when a group needs to land in the same room without coordinating clients.' },
    { id:'web',      label:'web, content & media',           color:'g-sun',    blurb:'flat-file CMS for git-as-database content, the design system every 247420 surface imports, the broadcast itself, and the pipelines that feed it.' },
    { id:'sandbox',  label:'browser sandboxes',              color:'g-purple', blurb:'real Linux userspaces, x86 boxes, and whole desktops that run inside a tab with no server doing the work — plus the fetch layer that gets them past CORS.' },
];



// ---- showcase enrichment ----
// Pulls richer per-project content (description, features, quickstart) from
// each gh-pages site at build time. Cached as lib/showcase.json. Failures fall
// back gracefully — UI uses projects.js blurb when showcase data is absent.

let _showcase = null;
let _showcasePromise = null;

export async function loadShowcase() {
    if (_showcase) return _showcase;
    if (_showcasePromise) return _showcasePromise;
    _showcasePromise = fetch('/lib/showcase.json', { cache:'no-cache' })
        .then(r => r.ok ? r.json() : {})
        .catch(() => ({}))
        .then(data => { _showcase = data; return data; });
    return _showcasePromise;
}

export function showcaseFor(code) {
    return _showcase && _showcase[code] && !_showcase[code].missing ? _showcase[code] : null;
}

// Activity lives on the showcase entry even when the gh-pages site is missing,
// so read the raw entry here (showcaseFor() hides missing entries). pushedAt +
// archived are written by scripts/fetch-showcase.mjs from the GitHub repo API.
export function activityFor(code) {
    const e = _showcase && _showcase[code];
    if (!e) return { pushedAt: null, archived: false, daysAgo: Infinity, tier: 1, commits14d: 0 };
    const archived = !!e.archived || !!e.disabled;
    const ts = e.pushedAt ? Date.parse(e.pushedAt) : NaN;
    const daysAgo = Number.isNaN(ts) ? Infinity : (Date.now() - ts) / 86400000;
    // commits14d excludes mechanical org-wide sweeps (malware-payload removal,
    // .gm state cleanup, etc.) that touch every repo the same day and would
    // otherwise make an untouched project look "active" purely from a bot pass.
    const commits14d = e.commits14d ?? 0;
    // tier: 2 = actually worked on (real commits in the last 14d), 1 = dormant
    // (pushed but no real recent commits, or pushed >30d ago), 0 = archived.
    const tier = archived ? 0 : (commits14d > 0 ? 2 : 1);
    return { pushedAt: e.pushedAt || null, archived, daysAgo, tier, commits14d };
}

// Feature what was actually worked on: rank by activity tier first (real
// recent commits > dormant > archived), then by commit count, then recency,
// then stars as the final tie-break. Stable for equal keys. Does not mutate
// the input array.
export function rankByActivity(list) {
    return [...list].sort((a, b) => {
        const ra = activityFor(a.code), rb = activityFor(b.code);
        if (rb.tier !== ra.tier) return rb.tier - ra.tier;
        if (rb.commits14d !== ra.commits14d) return rb.commits14d - ra.commits14d;
        if (ra.daysAgo !== rb.daysAgo) return ra.daysAgo - rb.daysAgo;
        const sa = (showcaseFor(a.code)?.stars ?? a.stars ?? 0);
        const sb = (showcaseFor(b.code)?.stars ?? b.stars ?? 0);
        return sb - sa;
    });
}
