// Project catalog — single source of truth for the AnEntrypoint expo.

export const projects = [
    // gm package — the factory + its rust internals
    { code:'001', title:'gm', sub:'convinces agents they are a state machine', cat:'gm', stars:15, color:'g-green', url:'https://github.com/AnEntrypoint/gm', tags:['flagship','state-machine','discipline'], install:'npx gm', body:'reach for gm when an agent is drifting — looping, hallucinating tools, skipping verification. drop it into any session and the model walks PLAN, EXECUTE, EMIT, VERIFY on every turn instead of guessing. it lives inside the agent loop, not beside it. exists because faith-based prompting stops being funny the second it ships to prod.' },
    { code:'003', title:'rs-search', sub:'RRF fusion + tokenization crate behind rs-plugkit\'s search', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/rs-search', tags:['rust','search'], install:'-', body:'not a standalone tool — no CLI, no MCP server, no binary. it\'s the dependency-free rlib rs-plugkit\'s wasm host links in for the actual ranking math: reciprocal rank fusion across ranked id lists (with an identifier-boost weight for camelCase/snake_case-shaped queries) and the tokenizer that splits camelCase/punctuation into searchable pieces. reach for it when you\'re touching how rs-plugkit merges or tokenizes search results, not when you want a search tool to run directly.' },
    { code:'004', title:'rs-codeinsight', sub:'tree-sitter codebase report generator for AI coding tools', cat:'gm', stars:1, color:'g-flame', url:'https://github.com/AnEntrypoint/rs-codeinsight', tags:['rust','tree-sitter','analysis'], install:'cargo install rs-codeinsight', body:'first call when an agent lands in an unfamiliar repo. one binary, 13 languages via tree-sitter, under 200ms even on 500-file projects — outputs a single ~900-token report with stack, routes, data models, env vars, conventions, test coverage, and health issues, no caps on the lists. exists so gm spends its tokens reasoning about the code, not re-deriving what the project even is one grep at a time.' },
    { code:'006', title:'rs-plugkit', sub:'the wasm engine gm actually runs on', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/rs-plugkit', tags:['rust','plugins'], install:'-', body:'the plugkit-core wasm guest that agentplug-runner loads to drive every gm dispatch — the FSM graph, the spool ABI, the git/prd/mutable verbs, all compiled in here. reach for it when you\'re changing how gm\'s phase machine or verb surface behaves, not when you\'re writing a new plugin — that\'s plugsdk. there\'s no standalone CLI or JS wasm-host fallback anymore; agentplug is the only host that loads it.' },
    { code:'009', title:'agentplug', sub:'the wasm plugin runtime gm actually runs on', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/agentplug', tags:['wasm','runtime','plugins'], install:'-', body:'the thing gm is not visible to you: one native runner hosts N wasm plugin modules (gm, libsql, bert, tree-sitter) and mediates calls between them, plus a direct-CDP browser driver and a native task registry — no per-host JS wrapper, no playwright dependency. every gm dispatch this session made went through it. reach for it when a plugin needs to run the same way across hosts without reimplementing the loader each time.' },
    { code:'010', title:'lean', sub:'an 8-phase, 5-gate method for agent-driven work', cat:'gm', stars:1, color:'g-flame', url:'https://github.com/AnEntrypoint/lean', tags:['method','skill','contracts'], install:'.claude/skills/lean/', body:'a sibling discipline to gm: the contract (types, names, signatures) is the durable artifact, not a spec file — a task is shaped, contracted, built, and checked by an agent that has not seen the implementation, with failure routed back to the phase that owns it. no comments, no example-based unit tests, no durable spec outside git. reach for it when you want gm-shaped rigor without gm\'s own state-machine framing.' },

    // gm ports — gm wired into every coding agent
    { code:'017', title:'agentgui', sub:'multi-agent GUI for AI coding assistants', cat:'gm-tools', stars:16, color:'g-sky', url:'https://github.com/AnEntrypoint/agentgui', tags:['gui','agents','desktop'], install:'npx agentgui', body:'open it when you run more than one coding agent and your terminal is a wreck. Claude Code, Gemini CLI, OpenCode — every session in one window with shared context. one npx, every agent. exists because alt-tabbing between four CLIs is not a workflow.' },
    { code:'018', title:'freddie', sub:'open JS agent harness with a dashboard on top', cat:'gm-tools', stars:5, color:'g-sky', url:'https://github.com/AnEntrypoint/freddie', tags:['dashboard','agents','observability'], install:'-', body:'reach for it when an agent needs more than a REPL — a full harness with 70 auto-discovered tools, a gateway fronting 17 platform adapters (discord, slack, whatsapp, telegram, matrix, and more), 8 pluggable memory providers, cron and batch runners, and an ACP server for IDE integration. the live dashboard is one view into that — the pane that shows what the fleet is doing — not the whole project anymore. built on pi-mono, xstate, and anentrypoint-design.' },
    { code:'019', title:'casey', sub:'animal-disease reporting over WhatsApp, for rural South Africa', cat:'gm-tools', stars:0, color:'g-sky', url:'https://github.com/AnEntrypoint/casey', tags:['agents','whatsapp','discord'], install:'-', body:'reach for it when the reporters are farmers and field workers texting in on WhatsApp, in their own language, about sick or dead livestock — casey greets them, gathers a structured report without interrogating them, and gives the organising team one observable case per report. built on freddie and thatcher, so the agent harness and the audited case system of record are already wired; the dashboard is a plain-language "needs you now" queue, not a ticket tracker. used when the people on both ends may not be technical and the priority stays with them, not with disease rules.' },
    { code:'020', title:'gmweb', sub:'Dockerized remote dev desktop for agentgui + opencode + gm', cat:'gm-tools', stars:2, color:'g-sky', url:'https://github.com/AnEntrypoint/gmweb', tags:['web','wasm','agents'], install:'-', body:'stand it up when you want a full remote desktop — VNC, web terminal, file manager — running Claude CLI, agentgui, and opencode behind one Traefik/nginx front door with HTTP Basic Auth on everything but the desktop route. it\'s a LinuxServer Webtop container with a supervisor that health-checks and auto-restarts those services, plus a background version-check loop that watches npm/GitHub for updates and bounces the affected service in place. used when the goal is a disposable, browser-reachable box that already has the agent stack installed, not a bare shell you have to provision by hand.' },
    { code:'086', title:'gm-mcp', sub:'MCP server exposing gm spool dispatch to any MCP client', cat:'gm-tools', stars:0, color:'g-sky', url:'https://github.com/AnEntrypoint/gm-mcp', tags:['mcp','gm','tool'], install:'-', body:'wraps gm whole spool write-then-poll-for-response cycle into one MCP tool call named gm, instead of a caller writing the input file, polling for the output file, and reading it as three separate steps. returns the response as flat YAML with opaque internal ids stripped and redundant nesting flattened. recent work made fs_read return file text verbatim instead of a YAML block scalar, and rejected malformed daemon owner locks.' },
    { code:'093', title:'uhh', sub:'casey, pre-configured for animal-disease surveillance', cat:'gm-tools', stars:0, color:'g-sky', url:'https://github.com/AnEntrypoint/uhh', tags:['agents','surveillance','casey'], install:'-', body:'casey pre-configured for animal-disease surveillance in rural South Africa, with every AnEntrypoint dependency - casey, acptoapi, design, freddie, thatcher - vendored as a git submodule for direct editing rather than resolved from a registry. casey itself is wired as a real local dependency, ready to edit in-tree. recent work added a contact.staff_state column for ranger focus and stale-write detection, and began fielding console words in the uhh vocabulary.' },

    // ml — tiny NPC dialog model, trained and run on our own iron
    { code:'014', title:'traintai', sub:'training pipeline for tai\'s NPC dialog model', cat:'gm', stars:1, color:'g-flame', url:'https://github.com/AnEntrypoint/traintai', tags:['rust','training','rl'], install:'uv run python src/round.py', body:'everything that produces the SillyTavern-shaped NPC dialog model tai runs: an economy simulation and survival-sim self-play tournament generate grounded training conversations, GRPO reinforcement learning scores adherence (persona, intent, grounding, action correctness against an oracle), and an autonomous multi-generation loop runs action-forge, tournament, prepare, SFT, GRPO, forge, then eval end to end with no human in the loop. exports straight to the int4 binary tai\'s runtime loads. consumed by tai as a git submodule.' },
    { code:'087', title:'gm-config', sub:'default config repo for gm, and the reference gm spec', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/gm-config', tags:['config','spec','prose'], install:'-', body:'every artifact under prose/, gates/, residual/, fsm/ and hooks/ is edited here directly, and rs-plugkit pulls from this repo at runtime - nothing generates it from a build and no CI overwrites a hand edit. rs-plugkit still ships each file as a compiled-in Rust default, used only when this repo is genuinely unreachable: offline, first dispatch before a cache exists, or a transient outage. recent work specified the trusted config source transports and raised index.max_file_bytes from 256 KiB to 2 MiB.' },
    { code:'089', title:'agentplug-bert', sub:'BGE-small embedding plugin for agentplug, candle-based', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/agentplug-bert', tags:['wasm','embeddings','rust'], install:'-', body:'a wasm32-wasip1 module exposing an embed capability to the agentplug runtime - BGE-small embeddings built on candle, so recall and memory get vectors without a sidecar service. recent work shipped the bert weights as f16 inside the wasm data segment, fixed a corrupted semver, and made signed plugin releases actually required instead of best-effort.' },
    { code:'090', title:'agentplug-crux', sub:'signal-concentration engine for workflow trace logs', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/agentplug-crux', tags:['wasm','logs','rust','analysis'], install:'-', body:'point it at a directory of low-signal-density logs and it dedups exact-repeat noise into shapes, builds frequency/transition/timing baselines over the deduped set, and emits a small uninterpreted dump of the statistically rarest shapes. nothing is an error or bad - a value is interesting because it is rare relative to the corpus, not because of what it means. ships as a native CLI and an agentplug wasm plugin from the same crate. recent work required signed plugin releases and synchronized the lockfile version.' },
    { code:'091', title:'agentplug-treesitter', sub:'multi-language tree-sitter parse and chunk extraction plugin', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/agentplug-treesitter', tags:['wasm','tree-sitter','parse'], install:'-', body:'a pure parse(path, source) capability for the agentplug runtime - multi-language tree-sitter parsing and chunk extraction with no DB or KV coupling, so the host decides what to do with the chunks. recent work declared the parser dependencies needed for host builds.' },
    { code:'092', title:'agentplug-libsql', sub:'libsql with vector search, as an agentplug plugin', cat:'gm', stars:0, color:'g-flame', url:'https://github.com/AnEntrypoint/agentplug-libsql', tags:['wasm','sqlite','vector','database'], install:'-', body:'a wasm32-wasip1 module exposing open/exec/query/prepare to the agentplug runtime through a handle table - libsql with vector search, so a plugin gets a real embedded database that also does embeddings, instead of shelling out to a sidecar.' },

    // voice + avatars
    { code:'030', title:'zellous', sub:'serverless Discord over Nostr', cat:'voice', stars:4, color:'g-flame', url:'https://github.com/AnEntrypoint/zellous', tags:['voice','opus','realtime'], install:'npm i zellous', body:'a full Discord-shaped chat and voice app with no backend — servers, channels, roles, threads, invite links — running entirely against public Nostr relays. voice is native WebRTC (mesh under 3 peers, elected SFU hub above that), signaling rides Nostr events, and there\'s no account system: your key is your identity, held in a browser extension or localStorage, with no password-reset path if you lose it. reach for it when you want Discord-like presence for a community without standing up any infrastructure at all — the whole client is a static site, and the protocol layer ships separately as wireweave.' },
    { code:'031', title:'wireweave', sub:'nostr + WebRTC networking SDK', cat:'voice', stars:1, color:'g-sky', url:'https://github.com/AnEntrypoint/wireweave', tags:['nostr','webrtc','sdk'], install:'npm i wireweave', body:'imported by anything in 247420 that needs peer discovery and realtime transport without a signaling server or a backend. nostr finds the peers; WebRTC carries voice, binary data channels, and now a full serverless chat layer — channels, servers, roles/bans, DMs, reactions, forum posts — all riding the same relay connection. used so voice and social features stay deployable without an ops team.' },
    { code:'094', title:'mc-420', sub:'right-to-repair live-performance workstation on a Pi 4', cat:'voice', stars:0, color:'g-mascot', url:'https://github.com/AnEntrypoint/mc-420', tags:['dsp','faust','audio','right-to-repair'], install:'-', body:'the codebase behind the MC-420, a right-to-repair live-performance workstation for punch-in musicians - looping, polyphonic pitch-lock, a granular/modal-resonator synth, hot-swappable effects - on a Raspberry Pi 4 running pure Linux, Alpine plus PREEMPT_RT. right-to-repair is the architecture and not a label: every algorithm is readable, editable Faust .dsp text a repair tech can open, not a firmware blob. recent work compiled the committed generated C++ in CI instead of running faust there, then ran the pitch-tracker suite against the real compiled engine.' },

    // data + memory + search
    { code:'042', title:'codebasesearch', sub:'semantic code search via Jina embeddings + LanceDB', cat:'data', stars:3, color:'g-acid', url:'https://github.com/AnEntrypoint/codebasesearch', tags:['search','codebase'], install:'-', body:'point it at a repo and ask english questions about the code instead of grepping for literal strings — "where do we handle auth", not "where does the string foo appear". runs as a CLI (`bunx codebasesearch`) or an MCP server Claude Code can call directly; single-shot, no daemon, auto-indexes into a local LanceDB store on first run and gitignores it. everything stays on-disk, no data leaves the machine.' },
    { code:'044', title:'busybase', sub:'drop-in self-hosted Supabase alternative', cat:'data', stars:1, color:'g-acid', url:'https://github.com/AnEntrypoint/busybase', tags:['sqlite','http','database'], install:'-', body:'reach for it when a project wants the Supabase JS v2 API — auth, tables, realtime — without Docker, Postgres, or a hosted bill. single Bun binary over libSQL/SQLite, Ed25519 keypair auth anonymous-first, built-in SMTP, pluggable hooks. used when "just give me a database with a URL" has grown into "and auth and realtime too."' },
    { code:'097', title:'npc', sub:'WebGPU trainer for NPC brains: PPO plus neuroevolution, one HTML file', cat:'data', stars:0, color:'g-acid', url:'https://github.com/AnEntrypoint/npc', tags:['webgpu','rl','ppo','training'], install:'node build.mjs', body:'trains plastic, self-pruning NPC brains for any real-time game on your own GPU - one HTML file, WebGPU, no Python, no server for training, with a CPU backend fallback when WebGPU is missing. node build.mjs stamps the artifact with a build hash of the template plus every inlined source, so --check proves the file you are testing was built from the sources you actually have and reports stale otherwise. recent work added a PPO league on realm v4.' },
    { code:'098', title:'liqology', sub:'liquid ontology: FAISS disambiguation over LLM interaction memory', cat:'data', stars:1, color:'g-acid', url:'https://github.com/AnEntrypoint/liqology', tags:['cpp','faiss','embeddings','memory'], install:'-', body:'codifies LLM and agent interactions over time: every call input/output pair is embedded, compared against prior activity via FAISS, and continuously reinforced or pruned by relevance, so an agent accumulated context stays useful without growing unboundedly. built on a C++23 boilerplate meant to close the ergonomic and distributability gap between C/C++ and Rust without leaving the C++ ecosystem, and ships a real agentplug wasm plugin for reinforce and prune.' },

    // tooling + bridges
    { code:'050', title:'ccsniff', sub:'Claude Code JSONL to events, history API, and audits', cat:'tooling', stars:2, color:'g-sun', url:'https://github.com/AnEntrypoint/ccsniff', tags:['observability','events'], install:'npm i ccsniff', body:'tail Claude Code\'s session JSONL and get a Node EventEmitter back, or a CLI to grep/rollup/tail sessions directly. used when something needs to react to what an agent is doing live — dashboards, hook triggers, audit logs — or when the sessions themselves need auditing: --git-discipline/--search-discipline/--verb-bypass-discipline/--spool-discipline catch gm sessions bypassing their own verb surfaces. also ships a mountable Express router (history snapshot/search/SSE stream) that AgentGUI\'s live client runs on, and an --unsloth export for turning session history into fine-tuning data. exists because Claude Code is otherwise an opaque box.' },
    { code:'051', title:'acptoapi', sub:'unified chain SDK + any-to-any AI protocol bridge', cat:'tooling', stars:5, color:'g-sun', url:'https://github.com/AnEntrypoint/acptoapi', tags:['shim','openai','acp'], install:'-', body:'reach for it when a codebase is wired to one SDK shape (OpenAI, Anthropic, Gemini) and needs to hit a different backend without a rewrite - point the SDK at acptoapi and it resolves a `provider/model` string to a concrete backend and streams back in the wire format the client expects. handles comma-separated fallback chains and named queues (an xstate v5 machine drives the descent, with per-provider backoff skipping known-down providers and a capability matrix keeping incapable models out of the chain). runs as a server-free programmatic SDK or as an HTTP server with OpenAI/Anthropic/Gemini-compatible endpoints; freddie, casey, and thebird all depend on it as the single source of truth for resolution and chaining instead of reimplementing it locally.' },
    { code:'054', title:'agent-gsuite', sub:'MCP server for Google Docs, Sheets, Gmail, Drive', cat:'tooling', stars:1, color:'g-sun', url:'https://github.com/AnEntrypoint/agent-gsuite', tags:['agents','gsuite'], install:'-', body:'reach for it when an agent needs to actually work inside a Google account — 53 MCP tools covering docs, sheets, gmail, drive, and apps script, plus an HTTP/SSE streaming mode with Google OAuth login for remote multi-user connections. used when the work crosses from "thinking about it" to "putting it in the user\'s inbox".' },
    { code:'056', title:'thatcher', sub:'config-driven application framework SDK', cat:'tooling', stars:0, color:'g-sun', url:'https://github.com/AnEntrypoint/thatcher', tags:['sdk','framework','config'], install:'-', body:'pulled in when an app should be described by config instead of wired by hand — the framework SDK extracted from moonlight and reused across casey and friends. used when the same application shape keeps getting rebuilt and it is time to declare it once.' },
    { code:'085', title:'obrowser', sub:'pure-Rust headless browser, also an agentplug wasm plugin', cat:'tooling', stars:0, color:'g-sun', url:'https://github.com/AnEntrypoint/obrowser', tags:['rust','browser','wasm','agents'], install:'-', body:'a browser engine written from scratch in Rust for automation, scraping and agent-driven workflows - not a Chromium fork, not a C++ wrapper. it also builds as a wasm32-wasip1 agentplug plugin, so the same engine drops into the plugin runtime gm already hosts. recent work fixed browser isolation and smoke startup.' },
    { code:'095', title:'goofedup', sub:'structural-anomaly watcher: catches malware by shape, not signature', cat:'tooling', stars:1, color:'g-sun', url:'https://github.com/AnEntrypoint/goofedup', tags:['security','anomaly','rust'], install:'-', body:'cross-platform watcher that catches malware by shape rather than signature, built after a Discord bootstrap file that should have been a 40-byte one-liner quietly ballooned into 270KB of obfuscated garbage, kept a polite .orig backup, and popped a node -e that phoned home to a C2 IP. recent work tuned the false alarms out of a 2026-09-30 log review: read-burst relaxation, watching npm lib/cli.js for growth before lifecycle scripts run, and capping first-run event-log replay to an hour.' },

    // p2p
    { code:'061', title:'spoint', sub:'multiplayer game server + netcode SDK', cat:'p2p', stars:2, color:'g-purple', url:'https://github.com/AnEntrypoint/spoint', tags:['discovery','p2p'], install:'-', body:'reach for it when a multiplayer game needs an authoritative server without hand-rolling netcode. Jolt physics, hot-reloadable apps for entity/world logic, a Three.js client, and lag compensation built in. one server handles both modes — `/` for real multiplayer over WebSocket, `/?singleplayer` runs the identical server code inside a Web Worker on the same origin. exports to a fully static, backend-less bundle for itch.io or GitHub Pages when a host with no server is the target.' },

    // web + content + media
    { code:'071', title:'247420', sub:'the proof of concept that runs live', cat:'web', stars:5, color:'g-green', url:'https://github.com/AnEntrypoint/247420', tags:['poc','spa','broadcast'], install:'git clone github.com/AnEntrypoint/247420', body:'the site you\'re reading. used as the pressure test for every gm and gm-cc pattern — real users, real timing, a broadcast TV system synced to the second. when something works here, the pattern ships. when it breaks here, it gets fixed before anyone else inherits it.' },
    { code:'072', title:'design', sub:'247420 design system', cat:'web', stars:1, color:'g-green', url:'https://github.com/AnEntrypoint/design', tags:['design-system','tokens'], install:'-', body:'imported by every 247420-shaped surface so they all look like they came from the same building. layered surfaces, monospace labels, loud content inside quiet chrome. used over a generic UI kit because the visual rhythm here is part of the brief, not the wrapping.' },
    { code:'088', title:'sembrowse', sub:'browser extension running constrained choice on local WebGPU', cat:'web', stars:0, color:'g-sky', url:'https://github.com/AnEntrypoint/sembrowse', tags:['browser','webgpu','extension'], install:'GitHub Releases', body:'a portable browser extension that runs SemIf-style constrained choice through a local WebGPU runtime when the browser exposes an adapter - no Python install, no service API, no API key, no hosted inference request, no native helper. model weights are intentionally not bundled. recent work made it wait for navigation to finish after each action, reject navigation to sites the goal and page never name, and delete a model-written planning step that measured no benefit.' },
    { code:'096', title:'livedesign', sub:'browser tab where Gemini Live edits a running Vite app', cat:'web', stars:0, color:'g-acid', url:'https://github.com/AnEntrypoint/livedesign', tags:['gemini','vite','live','agents'], install:'-', body:'a browser tab that streams your screen and microphone to a Gemini Live model. Gemini finds v0 templates, imports them, reads and edits files in app/, and Vite hot-reloads the result - it sees every build and runtime error its own edits caused, installs missing packages after a safety check, and can undo its changes. the key stays on the server; the browser only receives a short-lived single-use token with model, tools and system instruction locked. recent work hardened origin isolation, CSS policy and import resolution.' },

    // browser sandboxes — real Linux + desktops that run in a tab
    { code:'084', title:'litebox', sub:'sandboxing library OS that shrinks the host interface', cat:'sandbox', stars:0, color:'g-purple', url:'https://github.com/AnEntrypoint/litebox', tags:['rust','sandbox','library-os'], install:'-', body:'reach for it when a process should be sandboxed by shrinking the kernel surface it can see, not by filtering syscalls after the fact. a Rust library OS that cuts the host interface down to a thin shim layer - north shims above, south platforms below - so the same guest runs in kernel and non-kernel scenarios. recent work rebuilt the rootfs as a flat, pointer-free image with sorted children and fixed records, and taught idle host processes to empty their working set so their pages go to standby.' },
];

export const categories = [
    { id:'gm',       label:'gm — the factory + rust internals', color:'g-green',  blurb:'reach for these when an agent needs to plan, execute, search, orient, or remember. gm runs the loop; rs-exec, rs-search, rs-codeinsight, rs-learn, and rs-plugkit are the rust services it dispatches into during the loop.' },
    { id:'gm-tools', label:'gm ports — gm in every coding agent', color:'g-mascot', blurb:'pick the port that matches the editor or CLI you already live in. same loop, same discipline, every surface. agentgui is for when you run more than one at once.' },
    { id:'voice',    label:'voice + avatars',                color:'g-mascot', blurb:'used when a project needs to be heard or seen speaking — push-to-talk rooms, in-browser TTS, lipsync, VRM avatars opening their mouths.' },
    { id:'data',     label:'data, search & memory',          color:'g-acid',   blurb:'used when an agent needs memory that knows when, or search that understands what — temporal graphs and semantic codebase search.' },
    { id:'tooling',  label:'observability & shims',          color:'g-sun',    blurb:'reach for these when you need to watch an agent, point existing code at a different model, or bring an OpenAI-shaped client into the ACP world.' },
    { id:'p2p',      label:'peer-to-peer',                   color:'g-purple', blurb:'shared as a single link when a group needs to land in the same room without coordinating clients.' },
    { id:'web',      label:'web, content & media',           color:'g-sun',    blurb:'flat-file CMS for git-as-database content, the design system every 247420 surface imports, the broadcast itself, and the pipelines that feed it.' },
    { id:'sandbox',  label:'browser sandboxes',              color:'g-purple', blurb:'real Linux userspaces, x86 boxes, and whole desktops that run inside a tab with no server doing the work — plus the fetch layer that gets them past CORS.' },
];



// ---- showcase enrichment ----
// Pulls richer per-project content (description, features, quickstart) from
// each gh-pages site at build time. Cached as lib/showcase.json. Failures fall
// back gracefully — UI uses projects.js blurb when showcase data is absent.

let _showcase = null;
let _showcasePromise = null;

export async function loadShowcase() {
    if (_showcase) return _showcase;
    if (_showcasePromise) return _showcasePromise;
    _showcasePromise = fetch('/lib/showcase.json', { cache:'no-cache' })
        .then(r => r.ok ? r.json() : {})
        .catch(() => ({}))
        .then(data => { _showcase = data; return data; });
    return _showcasePromise;
}

export function showcaseFor(code) {
    return _showcase && _showcase[code] && !_showcase[code].missing ? _showcase[code] : null;
}

// Activity lives on the showcase entry even when the gh-pages site is missing,
// so read the raw entry here (showcaseFor() hides missing entries). pushedAt +
// archived are written by scripts/fetch-showcase.mjs from the GitHub repo API.
export function activityFor(code) {
    const e = _showcase && _showcase[code];
    if (!e) return { pushedAt: null, archived: false, daysAgo: Infinity, tier: 1, commits14d: 0 };
    const archived = !!e.archived || !!e.disabled;
    const ts = e.pushedAt ? Date.parse(e.pushedAt) : NaN;
    const daysAgo = Number.isNaN(ts) ? Infinity : (Date.now() - ts) / 86400000;
    // commits14d excludes mechanical org-wide sweeps (malware-payload removal,
    // .gm state cleanup, etc.) that touch every repo the same day and would
    // otherwise make an untouched project look "active" purely from a bot pass.
    const commits14d = e.commits14d ?? 0;
    // tier: 2 = actually worked on (real commits in the last 14d), 1 = dormant
    // (pushed but no real recent commits, or pushed >30d ago), 0 = archived.
    const tier = archived ? 0 : (commits14d > 0 ? 2 : 1);
    return { pushedAt: e.pushedAt || null, archived, daysAgo, tier, commits14d };
}

// Feature what was actually worked on: rank by activity tier first (real
// recent commits > dormant > archived), then by commit count, then recency,
// then stars as the final tie-break. Stable for equal keys. Does not mutate
// the input array.
export function rankByActivity(list) {
    return [...list].sort((a, b) => {
        const ra = activityFor(a.code), rb = activityFor(b.code);
        if (rb.tier !== ra.tier) return rb.tier - ra.tier;
        if (rb.commits14d !== ra.commits14d) return rb.commits14d - ra.commits14d;
        if (ra.daysAgo !== rb.daysAgo) return ra.daysAgo - rb.daysAgo;
        const sa = (showcaseFor(a.code)?.stars ?? a.stars ?? 0);
        const sb = (showcaseFor(b.code)?.stars ?? b.stars ?? 0);
        return sb - sa;
    });
}
